version: '3.9'
networks:
  mynetwork:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  main_app:
    image: ewa1234/main_app:2
    depends_on:
      - postgres
    container_name: main_app_compose
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    networks:
      - mynetwork
    ports:
      - "8080:8080"
volumes:
  pgdata: