spring:
  application:
    name: docker_project
  datasource:
    #    url: jdbc:postgresql://26.215.168.106:5432/mementauto
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  file:
    name: mydatabase.log
server:
  port: 8080
